# site name
prefixName: Cici's
siteName: blog~
# favicon and site master avatar
favicon: /img/favicon.ico
avatar: /img/avatar.webp
url: https://ljc0606.top
description: Life is just about enjoying living.
cdn: https://gitee.com/ljv0606/cdn/raw/master
pjax: 1
# 1开启
mathjax: 0

notice: 
lazyloadImg: https://gitee.com/ljv0606/cdn/raw/master/img/loading.gif

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    搞事情: {path: /categories/搞事情/, fa: fa-cloud-download }, 
    正经学: {path: /categories/正经学/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    电影: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  参考集: { path: /links/, fa: fa-link faa-shake }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://gitee.com/ljv0606/cdn/raw/master/img/0.webp
  - https://gitee.com/ljv0606/cdn/raw/master/img/1.webp
  - https://gitee.com/ljv0606/cdn/raw/master/img/2.webp
  - https://gitee.com/ljv0606/cdn/raw/master/img/3.webp
  - https://gitee.com/ljv0606/cdn/raw/master/img/4.webp
  - https://gitee.com/ljv0606/cdn/raw/master/img/5.webp
  - https://gitee.com/ljv0606/cdn/raw/master/img/6.webp
  - https://gitee.com/ljv0606/cdn/raw/master/img/7.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: 

# startdash url, title, desc img
startdash: 
  - {url: /categories/生活/, title: My Life, desc: 生活小记, img: /img/w1.webp}
  - {url: https://github.com/acdefg, title: My Github, desc: 本菜鸡的Github, img: /img/w2.webp}
  - {url: /categories/技术/, title: 学习笔记, desc: 记录一下小菜的学习过程, img: /img/w3.webp}


# your site build time or founded date
siteBuildingTime: 01/20/2022

#social  url, img PC端配置
social:
  github: {url: https://github.com/acdefg, img: /img/gitup.png}
  ljv0606@outlook.com: {url: /#, img: /img/email.jpg}
  gitee: {url: https://gitee.com/ljv0606, img: /img/gitee.jpg}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/acdefg, fa: fa-github, color: 333}
  gitee: {url: https://gitee.com/ljv0606, fa: fa-git, color: dd4b39}



# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://gitee.com/ljv0606/cdn/raw/master
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: yanshi.mp4
  
aplayer: 
  id: 2722953071
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: ySRMleyxDW43TSYlnWifvx99-gzGzoHsz
v_appKey: yn6scDoqTa50RWa6QSgcIA38

# Waline
waline:
  enable: false
  serverURL: #服务端地址
  visitor: false #统计阅读量
  comment_count: true #统计评论数
  avatar: mp # Gravatar style : mp/identicon/monsterid/wavatar/retro/hide
  guest_info: nick #,mail,link # custom comment header
  pageSize: 10
  placeholder: 祝开开心心！ # Comment Box placeholder
  requiredFields: [ 'nick','mail' ] #设置必填项
  background: https://gitee.com/cungudafa/source/raw/master/img/gif/Sitich/Sitich2.gif #输入框提示动画